begin;

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;
set local search_path = public, extensions;

create table if not exists public.agenda_respaldos (
  id bigint generated by default as identity primary key,
  creado_en timestamptz not null default now(),
  datos jsonb not null
);

insert into public.agenda_respaldos (datos)
select datos from public.agenda_estado where id = 'principal';

create table if not exists public.agenda_usuarios (
  usuario text primary key,
  clave_hash text not null,
  rol text not null check (rol in ('editora', 'soloVista')),
  nombre text not null,
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

insert into public.agenda_usuarios (usuario, clave_hash, rol, nombre)
select
  lower(trim(item->>'usuario')),
  crypt(item->>'clave', gen_salt('bf')),
  case when item->>'rol' = 'editora' then 'editora' else 'soloVista' end,
  coalesce(nullif(trim(item->>'nombre'), ''), item->>'usuario')
from public.agenda_estado,
jsonb_array_elements(coalesce(datos->'usuarios', '[]'::jsonb)) item
where id = 'principal'
  and nullif(trim(item->>'usuario'), '') is not null
  and nullif(item->>'clave', '') is not null
on conflict (usuario) do nothing;

do $$
begin
  if not exists (select 1 from public.agenda_usuarios) then
    raise exception 'No se encontraron usuarios actuales. La migración fue cancelada para proteger el acceso.';
  end if;
end;
$$;

create table if not exists public.agenda_sesiones (
  token_hash bytea primary key,
  usuario text not null references public.agenda_usuarios(usuario) on update cascade on delete cascade,
  creado_en timestamptz not null default now(),
  expira_en timestamptz not null,
  ultimo_uso timestamptz not null default now()
);

alter table public.agenda_usuarios enable row level security;
alter table public.agenda_sesiones enable row level security;
alter table public.agenda_respaldos enable row level security;

revoke all on public.agenda_usuarios, public.agenda_sesiones, public.agenda_respaldos from anon, authenticated;
revoke all on public.agenda_estado from anon, authenticated;

drop policy if exists "agenda_estado_select" on public.agenda_estado;
drop policy if exists "agenda_estado_insert" on public.agenda_estado;
drop policy if exists "agenda_estado_update" on public.agenda_estado;

update public.agenda_estado
set datos = datos - 'usuarios', actualizado_en = clock_timestamp()
where id = 'principal';

create or replace function public.agenda_listar_usuarios()
returns table(usuario text, nombre text, rol text)
language sql
security definer
set search_path = public, extensions
as $$
  select u.usuario, u.nombre, u.rol
  from public.agenda_usuarios u
  where u.activo = true
  order by u.nombre;
$$;

create or replace function public.agenda_iniciar_sesion(p_usuario text, p_clave text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  u public.agenda_usuarios%rowtype;
  token text;
begin
  delete from public.agenda_sesiones where expira_en <= now();
  select * into u from public.agenda_usuarios
  where usuario = lower(trim(p_usuario)) and activo = true;
  if u.usuario is null or u.clave_hash <> crypt(p_clave, u.clave_hash) then
    raise exception 'USUARIO_O_CLAVE_INCORRECTOS' using errcode = '28000';
  end if;
  token := encode(gen_random_bytes(32), 'hex');
  insert into public.agenda_sesiones(token_hash, usuario, expira_en)
  values (digest(token, 'sha256'), u.usuario, now() + interval '30 days');
  return jsonb_build_object('token', token, 'usuario', u.usuario, 'nombre', u.nombre, 'rol', u.rol);
end;
$$;

create or replace function public.agenda_obtener_estado(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  u public.agenda_usuarios%rowtype;
  e public.agenda_estado%rowtype;
begin
  select au.* into u
  from public.agenda_sesiones s
  join public.agenda_usuarios au on au.usuario = s.usuario
  where s.token_hash = digest(p_token, 'sha256') and s.expira_en > now() and au.activo = true;
  if u.usuario is null then raise exception 'SESION_INVALIDA' using errcode = '28000'; end if;
  update public.agenda_sesiones set ultimo_uso = now() where token_hash = digest(p_token, 'sha256');
  select * into e from public.agenda_estado where id = 'principal';
  return jsonb_build_object(
    'datos', e.datos,
    'version', e.actualizado_en,
    'usuario', jsonb_build_object('usuario', u.usuario, 'nombre', u.nombre, 'rol', u.rol)
  );
end;
$$;

create or replace function public.agenda_guardar_estado(p_token text, p_datos jsonb, p_version timestamptz)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  rol_actual text;
  version_nueva timestamptz;
  estado_actual public.agenda_estado%rowtype;
begin
  select au.rol into rol_actual
  from public.agenda_sesiones s
  join public.agenda_usuarios au on au.usuario = s.usuario
  where s.token_hash = digest(p_token, 'sha256') and s.expira_en > now() and au.activo = true;
  if rol_actual is null then raise exception 'SESION_INVALIDA' using errcode = '28000'; end if;
  if rol_actual <> 'editora' then raise exception 'SOLO_LECTURA' using errcode = '42501'; end if;

  update public.agenda_estado
  set datos = p_datos - 'usuarios', actualizado_en = clock_timestamp()
  where id = 'principal' and actualizado_en = p_version
  returning actualizado_en into version_nueva;

  if version_nueva is null then
    select * into estado_actual from public.agenda_estado where id = 'principal';
    return jsonb_build_object('ok', false, 'conflicto', true, 'datos', estado_actual.datos, 'version', estado_actual.actualizado_en);
  end if;
  return jsonb_build_object('ok', true, 'version', version_nueva);
end;
$$;

create or replace function public.agenda_guardar_usuario(
  p_token text, p_original text, p_usuario text, p_nombre text,
  p_clave text, p_rol text, p_codigo text default null
)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  actual text;
  es_nuevo boolean := nullif(trim(p_original), '') is null;
begin
  select au.usuario into actual from public.agenda_sesiones s join public.agenda_usuarios au on au.usuario=s.usuario
  where s.token_hash=digest(p_token,'sha256') and s.expira_en>now() and au.activo and au.rol='editora';
  if actual is null then raise exception 'SIN_PERMISO' using errcode='42501'; end if;
  if p_usuario !~ '^[a-z0-9._-]{3,24}$' or nullif(trim(p_nombre),'') is null or p_rol not in ('editora','soloVista') then
    raise exception 'DATOS_INCORRECTOS';
  end if;
  if es_nuevo then
    if p_codigo <> '2009' or length(coalesce(p_clave,'')) < 4 then raise exception 'CODIGO_O_CLAVE_INVALIDOS'; end if;
    insert into public.agenda_usuarios(usuario,clave_hash,rol,nombre)
    values(lower(p_usuario),crypt(p_clave,gen_salt('bf')),p_rol,trim(p_nombre));
  else
    if p_original <> p_usuario then
      update public.agenda_usuarios set usuario=lower(p_usuario) where usuario=p_original;
    end if;
    update public.agenda_usuarios set nombre=trim(p_nombre), rol=p_rol,
      clave_hash=case when nullif(p_clave,'') is null then clave_hash else crypt(p_clave,gen_salt('bf')) end,
      actualizado_en=now() where usuario=lower(p_usuario);
  end if;
  return true;
end;
$$;

create or replace function public.agenda_eliminar_usuario(p_token text, p_usuario text)
returns boolean language plpgsql security definer set search_path=public,extensions as $$
declare actual text;
begin
  select au.usuario into actual from public.agenda_sesiones s join public.agenda_usuarios au on au.usuario=s.usuario
  where s.token_hash=digest(p_token,'sha256') and s.expira_en>now() and au.activo and au.rol='editora';
  if actual is null or actual=p_usuario then raise exception 'SIN_PERMISO' using errcode='42501'; end if;
  if (select rol from public.agenda_usuarios where usuario=p_usuario)='editora'
    and (select count(*) from public.agenda_usuarios where rol='editora' and activo) <= 1 then
    raise exception 'SE_NECESITA_EDITORA';
  end if;
  delete from public.agenda_usuarios where usuario=p_usuario;
  return true;
end;
$$;

create or replace function public.agenda_cambiar_clave(p_token text, p_anterior text, p_nueva text)
returns boolean language plpgsql security definer set search_path=public,extensions as $$
declare u public.agenda_usuarios%rowtype;
begin
  select au.* into u from public.agenda_sesiones s join public.agenda_usuarios au on au.usuario=s.usuario
  where s.token_hash=digest(p_token,'sha256') and s.expira_en>now() and au.activo;
  if u.usuario is null or u.clave_hash<>crypt(p_anterior,u.clave_hash) then raise exception 'CLAVE_INCORRECTA' using errcode='28000'; end if;
  if length(p_nueva)<4 then raise exception 'CLAVE_CORTA'; end if;
  update public.agenda_usuarios set clave_hash=crypt(p_nueva,gen_salt('bf')), actualizado_en=now() where usuario=u.usuario;
  return true;
end;
$$;

create or replace function public.agenda_cerrar_sesion(p_token text)
returns void language sql security definer set search_path=public,extensions as $$
  delete from public.agenda_sesiones where token_hash=digest(p_token,'sha256');
$$;

drop function if exists public.registrar_push(text,text,text,text,text);

create or replace function public.registrar_push(
  p_token text, p_endpoint text, p_p256dh text, p_auth text, p_usuario text, p_nombre text
)
returns boolean language plpgsql security definer set search_path=public,extensions as $$
declare sesion_usuario text;
begin
  select au.usuario into sesion_usuario
  from public.agenda_sesiones s join public.agenda_usuarios au on au.usuario=s.usuario
  where s.token_hash=digest(p_token,'sha256') and s.expira_en>now() and au.activo;
  if sesion_usuario is null or sesion_usuario<>p_usuario then raise exception 'SESION_INVALIDA' using errcode='28000'; end if;
  if char_length(p_endpoint) not between 20 and 2000
    or char_length(p_p256dh) not between 20 and 500
    or char_length(p_auth) not between 5 and 500 then raise exception 'SUSCRIPCION_INVALIDA'; end if;
  insert into public.push_suscripciones(endpoint,p256dh,auth,usuario,nombre,activa,actualizado_en)
  values(p_endpoint,p_p256dh,p_auth,p_usuario,p_nombre,true,now())
  on conflict(endpoint) do update set p256dh=excluded.p256dh, auth=excluded.auth,
    usuario=excluded.usuario, nombre=excluded.nombre, activa=true, actualizado_en=now();
  return true;
end;
$$;

revoke all on public.push_suscripciones from anon, authenticated;
drop policy if exists "Registrar este dispositivo" on public.push_suscripciones;
drop policy if exists "Actualizar este dispositivo" on public.push_suscripciones;

revoke all on function public.agenda_listar_usuarios() from public;
revoke all on function public.agenda_iniciar_sesion(text,text) from public;
revoke all on function public.agenda_obtener_estado(text) from public;
revoke all on function public.agenda_guardar_estado(text,jsonb,timestamptz) from public;
revoke all on function public.agenda_guardar_usuario(text,text,text,text,text,text,text) from public;
revoke all on function public.agenda_eliminar_usuario(text,text) from public;
revoke all on function public.agenda_cambiar_clave(text,text,text) from public;
revoke all on function public.agenda_cerrar_sesion(text) from public;
revoke all on function public.registrar_push(text,text,text,text,text,text) from public;

grant execute on function public.agenda_listar_usuarios() to anon, authenticated;
grant execute on function public.agenda_iniciar_sesion(text,text) to anon, authenticated;
grant execute on function public.agenda_obtener_estado(text) to anon, authenticated;
grant execute on function public.agenda_guardar_estado(text,jsonb,timestamptz) to anon, authenticated;
grant execute on function public.agenda_guardar_usuario(text,text,text,text,text,text,text) to anon, authenticated;
grant execute on function public.agenda_eliminar_usuario(text,text) to anon, authenticated;
grant execute on function public.agenda_cambiar_clave(text,text,text) to anon, authenticated;
grant execute on function public.agenda_cerrar_sesion(text) to anon, authenticated;
grant execute on function public.registrar_push(text,text,text,text,text,text) to anon, authenticated;

commit;
