create table if not exists public.push_suscripciones (
  endpoint text primary key,
  p256dh text not null,
  auth text not null,
  usuario text not null,
  nombre text not null,
  activa boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists public.push_envios (
  id bigint generated by default as identity primary key,
  cita_id text not null,
  minutos_antes integer not null,
  endpoint text not null,
  enviado_en timestamptz not null default now(),
  unique (cita_id, minutos_antes, endpoint)
);

alter table public.push_suscripciones enable row level security;
alter table public.push_envios enable row level security;

grant insert on table public.push_suscripciones to anon;

drop policy if exists "Registrar este dispositivo" on public.push_suscripciones;
create policy "Registrar este dispositivo"
on public.push_suscripciones
for insert
to anon
with check (
  char_length(endpoint) between 20 and 2000
  and char_length(p256dh) between 20 and 500
  and char_length(auth) between 5 and 500
);

-- No se crean políticas de lectura: los celulares no pueden consultar
-- las suscripciones de otros dispositivos. La Edge Function usa service_role.
