create table if not exists public.whatsapp_mensajes (
  id bigint generated by default as identity primary key,
  telefono text not null,
  wa_id text,
  nombre text,
  direccion text not null check (direccion in ('entrante', 'saliente')),
  tipo text not null default 'text',
  texto text,
  message_id text not null unique,
  estado text,
  leido boolean not null default false,
  raw jsonb,
  creado_en timestamptz not null default now()
);

create index if not exists whatsapp_mensajes_telefono_creado_idx
  on public.whatsapp_mensajes (telefono, creado_en desc);

alter table public.whatsapp_mensajes enable row level security;
revoke all on table public.whatsapp_mensajes from anon, authenticated;

-- La app no lee esta tabla directo. La Edge Function whatsapp-inbox usa service_role
-- para recibir webhooks de Meta y para responder desde la bandeja de la app.
